name: 'IIS Site Action'

description: 'This action can start, stop, or restart an On-Prem IIS website'

inputs:
  action:
    description: Specify start, stop, restart as the action to perform
    default: 'start'
    required: true
  server:
    description: 'The name of the target server'
    required: true
  website-name:
    description: 'The name of the website to perform action on'
    required: true
  service-account-id:
    description: 'The service account name'
    required: true
  service-account-password:
    description: 'The service account password'
    required: true
  server-public-key:
    description: 'Path to remote server public ssl key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Action
      id: action
      shell: powershell
      run: |
        $secure_password = ConvertTo-SecureString -String ${{ inputs.service-account-password }} -AsPlainText -Force
        ${{ github.action_path }}/iis_action.ps1 `
          -action '${{ inputs.action }}' `
          -server '${{ inputs.server }}' `
          -website_name '${{ inputs.website-name }}' `
          -user_id '${{ inputs.service-account-id }}' `
          -password $secure_password `
          -cert_path '${{ inputs.server-public-key }}'
